name: React CI/CD

on:
  push:
    branches: [master]
  release:
    types: [created]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version}}
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run build --if-present
      - run: mv /Users/fdileo/Desktop/hello-react/build /Users/fdileo/Desktop/hello-react/helloreact
