name: React CI/CD

on:
  release:
    types: [created]

env:
  AZURE_WEBAPP_NAME: your-app-name # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: "10.x" # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: self-hosted
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: [14.x]
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
