name: React CI/CD

on:
  push:
    branches: [master]
  release:
    types: [created]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: self-hosted
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: [14.x]
      - name: npm install, build
        run: |
          npm i
          npm run build
